name: PR Build

permissions:
  contents: read
  packages: read

on:

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main

jobs:

  pr-build:
    uses: ritterim/public-github-actions/.github/workflows/npm-packages-pr-build.yml@v1.9.0
    #uses: ./.github/workflows/npm-packages-pr-build.yml
    with:
      always_increment_patch_version: true
      npm_package_name: skellycss
      run_tests: false
